#include "gpio.h"
#include "avr/io.h" /* To use the IO Ports Registers */
#include "avr/iom323.h"
/*
 * 1.PORTA...PORTD
 * 2.PORT_Pin0, PORT_Pin1, ... , PORT_Pin38, PORT_Pin39
 * 3.PORT_PIN_IN, PORT_PIN_OUT
 * 4.OFF,PULL_UP
 * 5.GPIO_PinLevelValue,PORT_PIN_LEVEL_HIGH
 * */

const GPIO_ConfigType GPIO_ConfigPin[TOTAL_PINS_NUM]={

				{PORTA_ID,PIN0 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTA_ID,PIN1 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTA_ID,PIN2 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTA_ID,PIN3 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTA_ID,PIN4 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTA_ID,PIN5 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTA_ID,PIN6 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTA_ID,PIN7 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},

				{PORTB_ID,PIN0 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTB_ID,PIN1 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTB_ID,PIN2 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTB_ID,PIN3 , PIN_OUTPUT, GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTB_ID,PIN4 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTB_ID,PIN5 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTB_ID,PIN6 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTB_ID,PIN7 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},

				{PORTC_ID,PIN0 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTC_ID,PIN1 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTC_ID,PIN2 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTC_ID,PIN3 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTC_ID,PIN4 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTC_ID,PIN5 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTC_ID,PIN6 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTC_ID,PIN7 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},

				{PORTD_ID,PIN0 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTD_ID,PIN1 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTD_ID,PIN2 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTD_ID,PIN3 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTD_ID,PIN4 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTD_ID,PIN5 , PIN_INPUT , GPIO_OFF , GPIO_PIN_LEVEL_LOW},
				{PORTD_ID,PIN7 , PIN_OUTPUT, GPIO_OFF , GPIO_PIN_LEVEL_LOW}

};
